In [5]:
! pip install Pillow #### For images install pillow

In [123]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, Flatten, MaxPool2D,MaxPooling2D
from tensorflow.keras import utils 
import PIL
from PIL import Image
import os
import matplotlib.pyplot as plt
import numpy as np
import sklearn
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split 
from numpy import *

In [124]:
path1='E:\\CNN Non Glucoma and Glucoma Images'
path2='E:\\CNN NO Glocama Resized'

In [125]:
# I have loaded all the files in one floder that is 80 images includes Glucoma and Non Glucoma
listing=os.listdir(path1)
num_samples=size(listing)
num_samples

80

In [126]:
# Resized all the images with 256,256
img_rows=248
img_cols=248
num_channel=2

img_data_list=[]

In [127]:
# All the resized images are stored in the  imlist 

for file in listing:
    im = Image.open(path1 +'\\' + file)
    img = im.resize((img_rows,img_cols))
    #Image.convert('rgb')
    img.save(path2 + '\\' + file)

imlist=os.listdir(path2)




In [128]:
img_data_list=[]
for i in imlist:
    im1=array(Image.open(path2+'\\'+i))
    img_data_list.append(im1)
img_data_list=np.asarray(img_data_list)

In [129]:
img_data_list.shape

(80, 248, 248, 3)

In [130]:
img_data_list[1]

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[8, 7, 7],
        [8, 6, 6],
        [9, 7, 7],
        ...,
        [7, 7, 7],
        [8, 7, 7],
        [8, 7, 7]],

       [[6, 6, 6],
        [7, 6, 7],
        [7, 6, 7],
        ...,
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[6, 6, 6],
        [7, 7, 8],
        [8, 7, 7],
        ...,
        [4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]]], dtype=uint8)

##  Creating Labels for Non Glucoma images=0 and  Glucoma images =1


In [132]:
# Creating Labels for Non Glucoma images=0 and  Glucoma images =1
label=np.ones((num_samples,),dtype=int)
label[0:41]=0
label[41:81]=1

In [133]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [134]:
X=img_data_list
X=X/255.0
print(X.shape)
y=label
print(y.shape)

(80, 248, 248, 3)
(80,)


## Train and Test Spliting 

In [135]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)


In [136]:
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')


X_train shape: (64, 248, 248, 3)
64 train samples
16 test samples


In [137]:
y_test.shape

(16,)

## CNN model Building 

In [138]:
# Initialize the model
model = Sequential()

In [139]:
model.add(Conv2D(32, kernel_size=(3,3),padding='same', input_shape=(248,248,3)))## Number of filters=32 and filters _size=(3,3)

In [140]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [142]:
model.add(Conv2D(32, kernel_size=(3,3),padding='same'))

In [143]:
model.add(MaxPooling2D(pool_size=(2, 2)))

In [144]:
model.add(Flatten()) # Flattening the 2D arrays for fully connected layers

In [145]:
import tensorflow as tf

In [146]:
model.add(Dense(256, activation=tf.nn.relu))

In [147]:
model.add(tf.keras.layers.Dropout(0.1))

In [148]:
model.add(Dense(1,activation=tf.nn.sigmoid))

In [149]:
# compile the model
model.compile(optimizer='adam', 
              loss='binary_crossentropy', 
              metrics=['accuracy'])


In [150]:
#model.compile(loss='binary_crossentropy', optimizer='Rmsprop', metrics=['accuracy'])


In [151]:
hist = model.fit(X_train, y_train, batch_size=10, epochs=9)

Train on 64 samples
Epoch 1/9
64/64 [==============================] - 9s 139ms/sample - loss: 4.4899 - accuracy: 0.7344
Epoch 2/9
64/64 [==============================] - 7s 105ms/sample - loss: 0.5917 - accuracy: 0.9375
Epoch 3/9
64/64 [==============================] - 6s 100ms/sample - loss: 0.4109 - accuracy: 0.9844
Epoch 4/9
64/64 [==============================] - 7s 103ms/sample - loss: 0.4177 - accuracy: 0.9844
Epoch 5/9
64/64 [==============================] - 6s 99ms/sample - loss: 1.5968 - accuracy: 0.8594
Epoch 6/9
64/64 [==============================] - 6s 97ms/sample - loss: 0.5001 - accuracy: 0.9219
Epoch 7/9
64/64 [==============================] - 7s 103ms/sample - loss: 0.4989 - accuracy: 0.9062
Epoch 8/9
64/64 [==============================] - 6s 96ms/sample - loss: 0.1610 - accuracy: 0.9688
Epoch 9/9
64/64 [==============================] - 7s 106ms/sample - loss: 0.2290 - accuracy: 0.9844


In [152]:
# Predicting on test set
y_pred = model.predict(X_test) >0.5

In [153]:
# Evaluating using confusion matrix
from sklearn.metrics import confusion_matrix,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[ 6  0]
 [ 0 10]]


In [154]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        10

    accuracy                           1.00        16
   macro avg       1.00      1.00      1.00        16
weighted avg       1.00      1.00      1.00        16

